# Generated by Django 4.2.29 on 2026-05-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0003_doador_cnpj_doador_cpf_doador_usuario'),
        ('doacao', '0005_alter_doacao_doador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='doador.doador'),
        ),
    ]
